project:
  type: book
  output-dir: docs

book:
  title: "Modeling of Hydrological Systems in Semi-Arid Central Asia"
  author: "Tobias Siegfried and Beatrice Marti, [hydrosolutions GmbH](www.hydrosolutions.ch)"
  description: | 
    This text is intended for the modern study of hydrology and mathematical modeling of 
    hydrological systems in semi-arid Central Asia. It is geared towards students and teachers 
    that would like to learn about these topics in an applied manner. The book adopts an 
    open-educational philosophy and promotes the use of open data and free of charge software.
  cover-image: images/cover/applied_modeling_cover.png
  site-url: https://hydrosolutions.github.io/caham_book/
  repo-url: https://github.com/hydrosolutions/caham_book
  repo-branch: master
  repo-actions: [edit]
  sharing: [facebook, linkedin]
  date: "2022 Release"
  chapters:
    - index.qmd
    - preface.qmd
    - study_guide_materials.qmd
    - part: hydrology_of_central_asia.qmd
      chapters: 
        - hydrological_systems.qmd
        - example_river_basins.qmd
    - part: data.qmd
      chapters:
        - data_sources.qmd
        - discharge_station_data.qmd
        - geospatial_data.qmd
        - snow_and_glacier_data.qmd
        - climate_data.qmd
    - part: hydrological_modeling.qmd
      chapters:
        - hydraulic_hydrological_modeling.qmd
        - long_term_water_balance_modeling.qmd
        - modeling_using_predictive_inference.qmd
        - real_world_examples.qmd
  appendices:
    - appendix_a_free_software.qmd
    - appendix_b_riverscentralasia_r_toolbox.qmd
    - appendix_c_quick_guides.qmd
    - appendix_d_exercise_solutions.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
    number-depth: 3
  pdf:
    documentclass: scrreprt

editor: text

