# Part III: Hydrological Modeling & Applications {#sec-hydrological-modeling}

This part of the book focuses on different types of hydrological modeling approaches and applications. The [Chapter on hydrological modeling using rainfall-runoff models](#sec-hydraulic-hydrological-modeling) introduces modeling using the free-to-use [RSMinerve Software Suite](https://www.crealp.ch/fr/accueil/outils-services/logiciels/rs-minerve.html){target="_blank"} in a hands-on manner. These types of models are foundational, for example, for basin planning exercises where tradeoffs between water for different sectoral allocations need to be quantified in a specific context.

Such models are also crucial for detailed climate impact studies regularly used to study these. The idea is simple, i.e., to utilize available climate model output over the 21^st^ century as forcing and investigating changes in the hydrographs at stations of interest over time. When different models and scenarios are run, a band of uncertainty relevant to any decision-making context can be specified.

Finally, the design of hydropower infrastructure depends on hydrological assessments with such types of models. The model outputs, i.e., simulated (modeled) discharge at a particular location, can be used to compute cumulative flow duration curves, which are essential for assessing the hydropower potential of a site and critically informing infrastructure sizing.

The relevance of these types of models for water planners and managers in the global drylands cannot be overstated. Therefore, one of the primary goals of this course is to familiarize the students well with such types of models.

The [Chapter on long-term hydrological modeling using the Budyko framework](#sec-budyko-modeling) looks at the greater semi-arid Central Asia region compared to individual catchments. It is at this scale and over many smaller catchments where interesting steady-state patterns of the partitioning of available water into evaporation and runoff can be studied under current and future climate states. Among other applications, such models can help to inform large-scale questions about the current and future interstate water distribution.

Finally, the [Chapter on time series modeling using predictive inference](#sec-modeling-using-predictive-inference) discusses models that learn from past patterns to predict the future without explicit water balance constraints. Through the learning of patterns in time-ordered (time series) data, possibly also with the help of auxiliary data such as snow cover, snow water equivalent, or climate forcing and forecasts, it has been shown that time series models can be powerful in predicting discharge at particular locations for different lead times, from hours to seasons. The section will present such approaches in the context of the seasonal forecasting of river flows in Central Asia.
